import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/Components/Header/Header";
import Footer from "./../Components/Homepage/Footer/Footer";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={`${inter.className} b w-full h-full`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
